/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sun.glass.events.KeyEvent;
import com.sv.udb.clases.Ejercicio2;
import java.util.*;
import javax.swing.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Jose Lira
 */
public class FrmEjerc2 extends javax.swing.JFrame {

    /**
     * Creates new form FrmEjerc2
     */
    private boolean isCant;
    private Ejercicio2 objeEjer;
   private List<Ejercicio2> listEjer;
    public FrmEjerc2() {
        initComponents();
           this.setLocationRelativeTo(null);
           this.txtIngresos.setFocusable(true);
           this.isCant = true;
           this.listEjer= new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIngresos = new javax.swing.JTextField();
        lblIngreso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtIngresos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIngresosKeyPressed(evt);
            }
        });

        lblIngreso.setText("Ingrese la cantidad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIngresos)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIngreso)
                        .addGap(0, 238, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblIngreso)
                .addGap(18, 18, 18)
                .addComponent(txtIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngresosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresosKeyPressed
if (evt.getKeyCode()== KeyEvent.VK_ENTER)
{
    String text = this.txtIngresos.getText();
    if(text.trim().length()>0)
    {
        if(this.isCant)
        {
            this.objeEjer= new Ejercicio2();
            this.objeEjer.setCant(Integer.parseInt(text));
            this.lblIngreso.setText("Ingrese la denominacion");
            this.txtIngresos.setText("");
        
        }
        else 
        {
            this.objeEjer.setDenoDine(Double.parseDouble(text));
            this.listEjer.add(this.objeEjer);
             this.lblIngreso.setText("Ingrese la cantidad: ");
             this.txtIngresos.setText("");
        }
        this.isCant = ! this.isCant;
        
    }
    else
    {
    JOptionPane.showMessageDialog(this, "El texto esta vacio");
    }
}
else if (evt.getKeyCode()==KeyEvent.VK_X)
{
    double tota = 0;
    for(Ejercicio2 temp: this.listEjer)
    {
     tota = tota + (temp.getCant()* temp.getDenoDine());   
    }
JOptionPane.showMessageDialog(this, "La respuesta es: "+tota);
}

    }//GEN-LAST:event_txtIngresosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEjerc2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JTextField txtIngresos;
    // End of variables declaration//GEN-END:variables
}
